spring.application.name=takip

# --- Database Connection ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# --- Hibernate Settings ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT & Reset Settings ---
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.password-reset.expiration=${RESET_EXP:15}

# --- Gmail SMTP Settings ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# --- Frontend URL Config ---
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# --- JWT Cookie Settings ---
application.security.jwt.cookie-name=${JWT_COOKIE_NAME:ddo_token}
application.security.jwt.cookie-secure=${JWT_COOKIE_SECURE:false}

upload.storage.path=${UPLOAD_PATH:uploads/}
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB